# Generated by Django 5.1.6 on 2025-03-31 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StandardRecipe',
        ),
    ]
